var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);
var restify = require('restify');
var builder = require('botbuilder');





// bot
// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});
  
// Create chat bot
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());

//=========================================================
// Bots Dialogs
//=========================================================
//global.address = {};

bot.dialog('/', function (session) {
    global.address = session.message.address;
    console.log(address);
    session.send("Generated by bot");
    io.emit('chat message', session.message.text);
});

//bot.dialog('/human', function (session, args) {
//    global.address = session.message.address;
//    console.log(args.promptText);
//    session.send(args.promptText);
    //io.emit('chat message', session.message.text);
//});



// sockets

app.get('/', function(req, res){
  res.sendfile('index.html');
});

io.on('connection', function(socket){
socket.on('disrupt', function(msg) {
  console.log('disrupting the bot');
});

  socket.on('chat message', function(msg){
    // i guess here we broadcast to bot builder
    io.emit('chat message', msg);

if (global.address) {
        var botmsg = new builder.Message()
        .address(global.address)
        .text(msg);
        //bot.beginDialog(global.address, '/human', {promptText: msg})
    bot.send(botmsg, function (err) {
        // Return success/failure
        console.log(err);
        //res.status(err ? 500 : 200);
        //res.end();
    });
} else {
  console.log('dont have any participants to send to ');
}

  });
});

http.listen(3000, function(){
  console.log('listening on *:3000');
});